name: Print Release Tag on PreRelease

on:
  release:
    types: [prereleased]

jobs:
  print_release_tag_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install deployment-time prerequisites
        run: |
         echo "Installing cx from Creoox/cx using token ${{ secrets.GH_TOKEN2 }}"
         curl -X GET -H "Authorization: token ${GH_TOKEN}" https://raw.githubusercontent.com/Creoox/cx/main/src/cx.clj > /usr/local/bin/cx
         chmod +x /usr/local/bin/cx
      - name: Notify about a new release
        run: | 
          cx teams notify \
          -w ${{ secrets.TEAMS_WEBHOOK }}" \
          -v "v${{ github.event.release.tag_name }}" \
          -s "New pre-release version of ifc2glbconverter" \
          -m "available to test" \
          -p "ifc2glbconverter" \
          -r "https://github.com/Creoox/creoox-ifc2gltfcxconverter" \
          -t "https://github.com/Creoox/creoox-ifc2gltfcxconverter"